[package]
name = "dbusify_hyper"
version = "0.1.0"
authors = ["Andrzej Ressel <jereksel@gmail.com>"]

[dependencies]
rspotify = { git = "https://github.com/jereksel/rspotify", rev = "3ddb1a01cb49cef985cd2dce8a4b6bee3f6ed40a" }
hyper = "0.12"
futures = "0.1.21"
webbrowser = "0.2.2"
